import json
import os

filepath = r"c:\Users\daver\Desktop\Ourania\OuraniaWindows\src\main\resources\data\interpretations.json"

with open(filepath, "r", encoding="utf-8") as f:
    data = json.load(f)

# The list of 360 Sabian Symbols
sabian_data = {
    # Aries
    "aries_1": "A woman has risen out of the ocean, a seal is embracing her.",
    "aries_2": "A comedian reveals human nature.",
    "aries_3": "The cameo profile of a man, suggesting the shape of his country.",
    "aries_4": "Two lovers strolling on a secluded walk.",
    "aries_5": "A triangle with wings.",
    "aries_6": "A square, with one of its sides brightly illumined.",
    "aries_7": "A man succeeds in expressing himself simultaneously in two realms.",
    "aries_8": "A large woman's hat with streamers blown by an east wind.",
    "aries_9": "A crystal gazer.",
    "aries_10": "A teacher gives new symbolic forms to traditional images.",
    "aries_11": "The ruler of a nation.",
    "aries_12": "A triangularly shaped flight of wild geese.",
    "aries_13": "An unexploded bomb reveals an unsuccessful social protest.",
    "aries_14": "A serpent coiling near a man and a woman.",
    "aries_15": "An Indian weaving a ceremonial blanket.",
    "aries_16": "Nature spirits are seen at work in the light of sunset.",
    "aries_17": "Two dignified spinsters sitting in silence.",
    "aries_18": "An empty hammock stretched between two trees.",
    "aries_19": "The magic carpet of Oriental imagery.",
    "aries_20": "A young girl feeding birds in winter.",
    "aries_21": "A pugilist entering the ring.",
    "aries_22": "The gate to the garden of all fulfilled desires.",
    "aries_23": "A pregnant woman in light summer dress.",
    "aries_24": "Blown inward by the wind, the curtains of an open window take the shape of a cornucopia.",
    "aries_25": "The possibility for man to gain experience at two levels of being.",
    "aries_26": "A man possessed of more gifts than he can hold.",
    "aries_27": "Through imagination a lost opportunity is regained.",
    "aries_28": "A large audience confronts the performer who disappointed its expectations.",
    "aries_29": "The music of the spheres.",
    "aries_30": "A duck pond and its brood.",
    # Taurus
    "taurus_1": "A clear mountain stream.",
    "taurus_2": "An electrical storm.",
    "taurus_3": "Natural steps lead to a lawn of clover in bloom.",
    "taurus_4": "The pot of gold at the end of the rainbow.",
    "taurus_5": "A widow at an open grave.",
    "taurus_6": "Cantilever bridge across a deep gorge.",
    "taurus_7": "The woman of Samaria at the ancestral well.",
    "taurus_8": "A sleigh on land uncovered by snow.",
    "taurus_9": "A fully decorated Christmas tree.",
    "taurus_10": "A Red Cross nurse.",
    "taurus_11": "A woman watering flowers in her garden.",
    "taurus_12": "A young couple window shopping.",
    "taurus_13": "A porter carrying heavy baggage.",
    "taurus_14": "On the beach, children play while shellfish grope at the edge of the water.",
    "taurus_15": "Head covered with a rakish silk hat, muffled against the cold, a man braves a storm.",
    "taurus_16": "An old teacher fails to interest his pupils in traditional knowledge.",
    "taurus_17": "A symbolical battle between swords and torches.",
    "taurus_18": "A woman airing an old bag through the open window of her room.",
    "taurus_19": "A new continent rising out of the ocean.",
    "taurus_20": "Wisps of winglike clouds flying across the sky.",
    "taurus_21": "A finger pointing to a line in an open book.",
    "taurus_22": "White dove flying over troubled waters.",
    "taurus_23": "A jewelry shop filled with valuable gems.",
    "taurus_24": "An Indian warrior riding fiercely, human scalps hanging from his belt.",
    "taurus_25": "A vast public park.",
    "taurus_26": "A Spanish gallant serenades his beloved.",
    "taurus_27": "An old Indian woman selling the artifacts of her tribe to passers-by.",
    "taurus_28": "A woman, past her change of life, experiences a new love.",
    "taurus_29": "Two cobblers working at a table.",
    "taurus_30": "A peacock parading on the terrace of an old castle.",
    # Gemini
    "gemini_1": "A glass-bottomed boat reveals under-sea wonders.",
    "gemini_2": "Santa Claus furtively filling stockings hanging in front of fireplace.",
    "gemini_3": "The garden of the Tuileries in Paris.",
    "gemini_4": "Holly and mistletoe reawaken old memories of Christmas.",
    "gemini_5": "A revolutionary magazine asking for action.",
    "gemini_6": "Workmen drilling for oil.",
    "gemini_7": "A well with bucket and rope under the shade of majestic trees.",
    "gemini_8": "Aroused strikers surround a factory.",
    "gemini_9": "A quiver filled with arrows.",
    "gemini_10": "An airplane performing a nose dive.",
    "gemini_11": "Newly opened lands offer the pioneer new opportunities for experience.",
    "gemini_12": "A Negro girl fights for her independence in the city.",
    "gemini_13": "A famous pianist giving a concert performance.",
    "gemini_14": "Bridging physical space and social distinctions, two men communicate telepathically.",
    "gemini_15": "Two Dutch children talking to each other, exchanging their knowledge.",
    "gemini_16": "A woman activist in an emotional speech dramatizing her cause.",
    "gemini_17": "The head of a robust youth changes into that of a mature thinker.",
    "gemini_18": "Two Chinese men converse in their native tongue in an American city.",
    "gemini_19": "A large archaic volume reveals a traditional wisdom.",
    "gemini_20": "A modern cafeteria displays an abundance of food, products of various regions.",
    "gemini_21": "A tumultuous labor demonstration.",
    "gemini_22": "Dancing couples in a harvest festival.",
    "gemini_23": "Three fledglings in a nest high in a tree.",
    "gemini_24": "Children skating over a frozen village pond.",
    "gemini_25": "A gardener trimming large palm trees.",
    "gemini_26": "Frost-covered trees against winter skies.",
    "gemini_27": "A gypsy emerging from the forest wherein her tribe is encamped.",
    "gemini_28": "Through bankruptcy, society gives to an overburdened individual the opportunity to begin again.",
    "gemini_29": "The first mockingbird of spring.",
    "gemini_30": "A parade of bathing beauties before large beach crowds.",
    # Cancer
    "cancer_1": "On a ship the sailors lower an old flag and raise a new one.",
    "cancer_2": "A man on a magic carpet hovers over a large expanse of land.",
    "cancer_3": "A man bundled in fur leads a shaggy deer.",
    "cancer_4": "A cat arguing with a mouse.",
    "cancer_5": "At a railroad crossing, an automobile is wrecked by a train.",
    "cancer_6": "Game birds feathering their nests.",
    "cancer_7": "Two nature spirits dancing under the moonlight.",
    "cancer_8": "A group of rabbits dressed in human clothes walk as if on parade.",
    "cancer_9": "A small, naked girl bends over a pond trying to catch a fish.",
    "cancer_10": "A large diamond in the first stages of the cutting process.",
    "cancer_11": "A clown caricaturing well-known personalities.",
    "cancer_12": "A Chinese woman nursing a baby whose aura reveals him to be the reincarnation of a great teacher.",
    "cancer_13": "A hand with a prominent thumb is held out for study.",
    "cancer_14": "A very old man facing a vast dark space to the northeast.",
    "cancer_15": "In a sumptuous dining hall guests relax after partaking of a huge banquet.",
    "cancer_16": "A man studying a mandala in front of him, with the help of a very ancient book.",
    "cancer_17": "The unfoldment of multilevel potentialities issuing from an original germ.",
    "cancer_18": "A hen scratching the ground to find nourishment for her progeny.",
    "cancer_19": "A priest performing a marriage ceremony.",
    "cancer_20": "Venetian gondoliers giving a serenade.",
    "cancer_21": "A famous singer is proving her virtuosity during an operatic performance.",
    "cancer_22": "A young woman awaiting a sailboat.",
    "cancer_23": "The meeting of a literary society.",
    "cancer_24": "A woman and two men castaways on a small island of the South Seas.",
    "cancer_25": "A will-o'-the-wisp takes on the shape of a man.",
    "cancer_26": "Guests are reading in the library of a luxurious home.",
    "cancer_27": "A violent storm in a canyon filled with expensive homes.",
    "cancer_28": "An Indian girl introduces her white lover to her assembled tribe.",
    "cancer_29": "A Greek muse weighing new born twins in golden scales.",
    "cancer_30": "A Daughter of the American Revolution.",
    # Leo
    "leo_1": "Blood rushes to a man's head as his vital energies are mobilized under the spur of ambition.",
    "leo_2": "An epidemic of mumps.",
    "leo_3": "A middle-aged woman, her long hair flowing over her shoulders and in a braless youthful garment.",
    "leo_4": "Formally dressed elderly man stands near trophies he brought back from a hunting expedition.",
    "leo_5": "Rock formations tower over a deep canyon.",
    "leo_6": "A conservative, old-fashioned lady is confronted by a 'hippie' girl.",
    "leo_7": "The constellations of stars shine brilliantly in the night sky.",
    "leo_8": "A communist activist spreading his revolutionary ideals.",
    "leo_9": "Glass blowers shape beautiful vases with their controlled breathing.",
    "leo_10": "Early morning dew sparkles as sunlight floods the field.",
    "leo_11": "Children play on a swing hanging from the branches of a huge oak tree.",
    "leo_12": "An evening party of adults on a lawn illumined by fancy lanterns.",
    "leo_13": "An old sea captain rocking himself on the porch of his cottage.",
    "leo_14": "A human soul seeking opportunities for outward manifestation.",
    "leo_15": "A pageant, with its spectacular floats, moves along a street crowded with cheering people.",
    "leo_16": "The storm ended, all nature rejoices in brilliant sunshine.",
    "leo_17": "A volunteer church choir singing religious hymns.",
    "leo_18": "A chemist conducts an experiment for his students.",
    "leo_19": "A houseboat party.",
    "leo_20": "Zuni Indians perform a ritual to the Sun.",
    "leo_21": "Intoxicated chickens dizzily flap their wings trying to fly.",
    "leo_22": "A carrier pigeon fulfilling its mission.",
    "leo_23": "In a circus the bareback rider displays her dangerous skill.",
    "leo_24": "Totally concentrated upon inner spiritual attainment, a man is sitting in a state of complete neglect of bodily appearance.",
    "leo_25": "A large camel is seen crossing a vast and forbidding desert.",
    "leo_26": "After the heavy storm, a rainbow.",
    "leo_27": "The luminescence of dawn in the eastern sky.",
    "leo_28": "Many little birds on a limb of a big tree.",
    "leo_29": "A mermaid emerges from the ocean waves ready for rebirth in human form.",
    "leo_30": "An unsealed letter.",
    # Virgo
    "virgo_1": "In a portrait, the significant features of a man's head are artistically emphasized.",
    "virgo_2": "A large white cross dominates the landscape.",
    "virgo_3": "Two guardian angels.",
    "virgo_4": "Black and white children play together happily.",
    "virgo_5": "A man becoming aware of nature spirits and normally unseen spiritual agencies.",
    "virgo_6": "A merry-go-round.",
    "virgo_7": "A harem.",
    "virgo_8": "A five-year-old child takes a first dancing lesson.",
    "virgo_9": "An expressionist painter at work.",
    "virgo_10": "Two heads looking out and beyond the shadows.",
    "virgo_11": "In her baby a mother sees her deep longing for a son answered.",
    "virgo_12": "After the wedding, the groom snatches the veil away from his bride.",
    "virgo_13": "A powerful statesman overcomes a state of political hysteria.",
    "virgo_14": "An aristocratic family tree.",
    "virgo_15": "A fine lace handkerchief, heirloom from valorous ancestors.",
    "virgo_16": "In the zoo, children are brought face to face with an orangutan.",
    "virgo_17": "A volcanic eruption.",
    "virgo_18": "An Ouija board.",
    "virgo_19": "A swimming race.",
    "virgo_20": "A caravan of cars headed to the West Coast.",
    "virgo_21": "A girls' basketball team.",
    "virgo_22": "A royal coat of arms enriched with precious stones.",
    "virgo_23": "A lion tamer displays his skill and character.",
    "virgo_24": "Mary and her little lamb.",
    "virgo_25": "A flag at half-mast in front of a public building.",
    "virgo_26": "A boy with a censer serves the priest near the altar.",
    "virgo_27": "A group of aristocratic ladies meet ceremonially at a court's function.",
    "virgo_28": "A baldheaded man who has seized power.",
    "virgo_29": "A seeker after occult knowledge is reading an ancient scroll which illumines his mind.",
    "virgo_30": "Totally intent upon completing an immediate task, a man is deaf to any allurement.",
    # Libra
    "libra_1": "In a collection of perfect specimens of many biological forms, a butterfly displays the beauty of its wings.",
    "libra_2": "The transmutation of the fruits of past experiences into the seed-realizations of the forever creative spirit.",
    "libra_3": "The dawn of a new day reveals everything changed.",
    "libra_4": "Around a campfire a group of young people sit in spiritual communion.",
    "libra_5": "A man revealing to his students the foundation of an inner knowledge upon which a 'new world' could be built.",
    "libra_6": "A man watches his ideals taking a concrete form before his inner vision.",
    "libra_7": "A woman feeding chickens and protecting them from the hawks.",
    "libra_8": "A blazing fireplace in a deserted home.",
    "libra_9": "Three 'old masters' hanging on the wall of a special room in an art gallery.",
    "libra_10": "Having passed safely through narrow rapids, a canoe reaches calm waters.",
    "libra_11": "A professor peering over his glasses at his students.",
    "libra_12": "Miners are surfacing from a deep coal mine.",
    "libra_13": "Children blowing soap bubbles.",
    "libra_14": "In the heat of the noon hour a man takes a siesta.",
    "libra_15": "Circular paths.",
    "libra_16": "After a storm a boat landing stands in need of reconstruction.",
    "libra_17": "A retired sea captain watches ships entering and leaving the harbor.",
    "libra_18": "Two men placed under arrest.",
    "libra_19": "A gang of robbers in hiding.",
    "libra_20": "A rabbi performing his duties.",
    "libra_21": "A Sunday crowd enjoying the beach.",
    "libra_22": "A child giving birds a drink at a fountain.",
    "libra_23": "Chanticleer's voice heralds sunrise.",
    "libra_24": "A butterfly with a third wing on its left side.",
    "libra_25": "The sight of an autumn leaf brings to a pilgrim the sudden revelation of the mystery of life and death.",
    "libra_26": "An eagle and a large white dove change into each other.",
    "libra_27": "An airplane sails, high in the clear sky.",
    "libra_28": "A man becoming aware of spiritual forces surrounding and assisting him.",
    "libra_29": "Mankind's vast and enduring effort to reach for knowledge transferable from generation to generation.",
    "libra_30": "Three mounds of knowledge on a philosopher's head.",
    # Scorpio
    "scorpio_1": "A crowded sightseeing bus on a city street.",
    "scorpio_2": "A delicate bottle of perfume lies broken, releasing its fragrance.",
    "scorpio_3": "A house-raising party in a small village enlists the neighbors' cooperation.",
    "scorpio_4": "A youth carries a lighted candle in a devotional ritual.",
    "scorpio_5": "A massive rocky shore resists the pounding of the sea.",
    "scorpio_6": "The gold rush tears men away from their native soil.",
    "scorpio_7": "Deep-sea divers.",
    "scorpio_8": "A calm lake bathed in moonlight.",
    "scorpio_9": "A dentist at work.",
    "scorpio_10": "A fellowship supper reunites old comrades.",
    "scorpio_11": "A drowning man is being rescued.",
    "scorpio_12": "An official embassy ball.",
    "scorpio_13": "An inventor performs a laboratory experiment.",
    "scorpio_14": "Telephone linemen at work installing new connections.",
    "scorpio_15": "Children playing around five mounds of sand.",
    "scorpio_16": "A girl's face breaking into a smile.",
    "scorpio_17": "A woman, fecundated by her own spirit, is 'great with child'.",
    "scorpio_18": "A path through woods brilliant with multicolored splendor.",
    "scorpio_19": "A parrot repeats the conversation he has overheard.",
    "scorpio_20": "A woman draws away two dark curtains closing the entrance to a sacred pathway.",
    "scorpio_21": "Obeying his conscience, a soldier resists orders.",
    "scorpio_22": "Hunters shooting wild ducks.",
    "scorpio_23": "A rabbit metamorphoses into a nature spirit.",
    "scorpio_24": "After having heard an inspired individual deliver his 'sermon on the mount,' crowds are returning home.",
    "scorpio_25": "An X-ray photograph.",
    "scorpio_26": "American Indians making camp after moving into a new territory.",
    "scorpio_27": "A military band marches noisily on through the city streets.",
    "scorpio_28": "The king of the fairies approaching his domain.",
    "scorpio_29": "An Indian squaw pleading to the chief for the lives of her children.",
    "scorpio_30": "Children in Halloween costumes indulge in various pranks.",
    # Sagittarius
    "sagittarius_1": "Retired army veterans gather to reawaken old memories.",
    "sagittarius_2": "White-capped waves display the power of wind over sea.",
    "sagittarius_3": "Two men playing chess.",
    "sagittarius_4": "A little child learning to walk with the encouragement of his parents.",
    "sagittarius_5": "An old owl sits alone on the branch of a large tree.",
    "sagittarius_6": "A game of cricket.",
    "sagittarius_7": "Cupid knocks at the door of a human heart.",
    "sagittarius_8": "Within the depths of the earth new elements are being formed.",
    "sagittarius_9": "A mother leads her small child step by step up a steep stairway.",
    "sagittarius_10": "A theatrical representation of a golden-haired goddess of opportunity.",
    "sagittarius_11": "In the left section of an archaic temple, a lamp burns in a container shaped like a human body.",
    "sagittarius_12": "A flag turns into an eagle; the eagle into a chanticleer saluting the dawn.",
    "sagittarius_13": "A widow's past is brought to light.",
    "sagittarius_14": "The Great Pyramid and the Sphinx.",
    "sagittarius_15": "The ground hog looking for its shadow on Groundhog Day.",
    "sagittarius_16": "Sea gulls fly around a ship in expectation of food.",
    "sagittarius_17": "An Easter sunrise service draws a large crowd.",
    "sagittarius_18": "Children playing on the beach, their heads protected by sunbonnets.",
    "sagittarius_19": "Pelicans menaced by the behavior and refuse of men seek safer areas for bringing up their young.",
    "sagittarius_20": "In an old-fashioned northern village men cut the ice of a frozen pond for use during the summer.",
    "sagittarius_21": "A child and a dog wearing borrowed eyeglasses.",
    "sagittarius_22": "A Chinese laundry.",
    "sagittarius_23": "A group of immigrants as they fulfill the requirements of entrance into the new country.",
    "sagittarius_24": "A bluebird perched on the door of a cottage.",
    "sagittarius_25": "A chubby boy on a hobby-horse.",
    "sagittarius_26": "A flag bearer in a battle.",
    "sagittarius_27": "A sculptor at his work.",
    "sagittarius_28": "An old bridge over a beautiful stream is still in constant use.",
    "sagittarius_29": "A fat boy mowing the lawn of his house on an elegant suburban street.",
    "sagittarius_30": "The Pope blessing the faithful.",
    # Capricorn
    "capricorn_1": "An Indian chief claims power from the assembled tribe.",
    "capricorn_2": "Three rose windows in a Gothic church, one damaged by war.",
    "capricorn_3": "A human soul, in its eagerness for new experiences, seeks embodiment.",
    "capricorn_4": "A group of people outfitting a large canoe at the start of a journey by water.",
    "capricorn_5": "Indians on the warpath. While some men row a well-filled canoe, others in it perform a war dance.",
    "capricorn_6": "Ten logs lie under an archway leading to darker woods.",
    "capricorn_7": "A veiled prophet speaks, seized by the power of a god.",
    "capricorn_8": "In a sunlit home domesticated birds sing joyously.",
    "capricorn_9": "An angel carrying a harp.",
    "capricorn_10": "An albatross feeding from the hand of a sailor.",
    "capricorn_11": "A large group of pheasant on a private estate.",
    "capricorn_12": "An illustrated lecture on natural science reveals little-known aspects of life.",
    "capricorn_13": "A fire worshiper meditates on the ultimate realities of existence.",
    "capricorn_14": "An ancient bas-relief carved in granite remains a witness to a long-forgotten culture.",
    "capricorn_15": "In a hospital, the children's ward is filled with toys.",
    "capricorn_16": "School grounds filled with boys and girls in gymnasium suits.",
    "capricorn_17": "A repressed woman finds a psychological release in nudism.",
    "capricorn_18": "The Union Jack flag flies from a British warship.",
    "capricorn_19": "A five-year-old child carrying a bag filled with groceries.",
    "capricorn_20": "A hidden choir is singing during a religious service.",
    "capricorn_21": "A relay race.",
    "capricorn_22": "By accepting defeat gracefully, a general reveals nobility of character.",
    "capricorn_23": "A soldier receiving two awards for bravery in combat.",
    "capricorn_24": "A woman entering a convent.",
    "capricorn_25": "A store filled with precious oriental rugs.",
    "capricorn_26": "A nature spirit dancing in the iridescent mist of a waterfall.",
    "capricorn_27": "Pilgrims climbing the steep steps leading to a mountain shrine.",
    "capricorn_28": "A large aviary.",
    "capricorn_29": "A woman reading tea leaves.",
    "capricorn_30": "A secret meeting of men responsible for executive decisions in world affairs.",
    # Aquarius
    "aquarius_1": "An old adobe mission in California.",
    "aquarius_2": "An unexpected thunderstorm.",
    "aquarius_3": "A deserter from the navy.",
    "aquarius_4": "A Hindu yogi demonstrates his healing powers.",
    "aquarius_5": "A council of ancestors is seen implementing the efforts of a young leader.",
    "aquarius_6": "A masked figure performs ritualistic acts in a mystery play.",
    "aquarius_7": "A child is seen being born out of an egg.",
    "aquarius_8": "Beautifully gowned wax figures on display.",
    "aquarius_9": "A flag is seen turning into an eagle.",
    "aquarius_10": "A man who had for a time become the embodiment of a popular ideal is made to realize that as a person he is not this ideal.",
    "aquarius_11": "During a silent hour, a man receives a new inspiration which may change his life.",
    "aquarius_12": "On a vast staircase stand people of different types, graduated upward.",
    "aquarius_13": "A barometer.",
    "aquarius_14": "A train entering a tunnel.",
    "aquarius_15": "Two lovebirds sitting on a fence and singing happily.",
    "aquarius_16": "A big businessman at his desk.",
    "aquarius_17": "A watchdog stands guard, protecting his master and his master's property.",
    "aquarius_18": "A man's secret motives are being publicly unmasked.",
    "aquarius_19": "A forest fire is being subdued by the use of water, chemicals and sheer muscular energy.",
    "aquarius_20": "A large white dove bearing a message.",
    "aquarius_21": "A disappointed and disillusioned woman courageously faces a seemingly empty life.",
    "aquarius_22": "A rug is placed on a floor for children to play on.",
    "aquarius_23": "A big bear sitting down and waving all its paws.",
    "aquarius_24": "A man, having overcome his passions, teaches deep wisdom in terms of his experience.",
    "aquarius_25": "A butterfly with the right wing more perfectly formed.",
    "aquarius_26": "A garage man testing a car's battery with a hydrometer.",
    "aquarius_27": "An ancient pottery bowl filled with fresh violets.",
    "aquarius_28": "A tree felled and sawed to ensure a supply of wood for the winter.",
    "aquarius_29": "A butterfly emerging from a chrysalis.",
    "aquarius_30": "Deeply rooted in the past of a very ancient culture, a spiritual brotherhood in which many individual minds are merged into the glowing light of a unanimous consciousness is revealed to one who has emerged successfully from his metamorphosis.",
    # Pisces
    "pisces_1": "In a crowded marketplace farmers and middlemen display a great variety of products.",
    "pisces_2": "A squirrel hiding from hunters.",
    "pisces_3": "Petrified tree trunks lie broken on desert sand.",
    "pisces_4": "Heavy car traffic on a narrow isthmus linking two seaside resorts.",
    "pisces_5": "A church bazaar.",
    "pisces_6": "A parade of army officers in full dress.",
    "pisces_7": "Illumined by a shaft of light, a large cross lies on rocks surrounded by sea mist.",
    "pisces_8": "A girl blowing a bugle.",
    "pisces_9": "A jockey spurs his horse, intent on outdistancing his rivals.",
    "pisces_10": "An aviator pursues his journey, flying through ground-obscuring clouds.",
    "pisces_11": "Men traveling a narrow path, seeking illumination.",
    "pisces_12": "In the sanctuary of an occult brotherhood, newly initiated members are being examined and their character tested.",
    "pisces_13": "An ancient sword, used in many battles, is displayed in a museum.",
    "pisces_14": "A lady wrapped in a large stole of fox fur.",
    "pisces_15": "An officer instructing his men before a simulated assault under a barrage of live shells.",
    "pisces_16": "In the quiet of his study a creative individual experiences a flow of inspiration.",
    "pisces_17": "An Easter parade.",
    "pisces_18": "In a gigantic tent, villagers witness a spectacular performance.",
    "pisces_19": "A master instructing his disciple.",
    "pisces_20": "A table set for an evening meal.",
    "pisces_21": "Under the watchful and kind eye of a Chinese servant, a girl fondles a little white lamb.",
    "pisces_22": "A prophet carrying tablets of the new law is walking down the slopes of Mount Sinai.",
    "pisces_23": "A 'materializing' medium giving a seance.",
    "pisces_24": "On a small island surrounded by the vast expanse of the sea, people are seen living in close interaction.",
    "pisces_25": "A religious organization succeeds in overcoming the corrupting influence of perverted practices and materialized ideals.",
    "pisces_26": "A New Moon reveals that it's time for people to go ahead with their different projects.",
    "pisces_27": "The harvest moon illumines a clear autumnal sky.",
    "pisces_28": "A fertile garden under the Full Moon reveals a variety of full-grown vegetables.",
    "pisces_29": "Light breaking into many colors as it passes through a prism.",
    "pisces_30": "A majestic rock formation resembling a face is idealized by a boy who takes it as his ideal of greatness, and as he grows up, begins to look like it."
}

data["sabian"] = sabian_data

with open(filepath, "w", encoding="utf-8") as f:
    json.dump(data, f, indent=2, ensure_ascii=False)

print("Successfully added Sabian Symbols to interpretations.json")
