package com.zodiacomputing.ourania.astro;

import de.thmac.swisseph.SweDate;
import de.thmac.swisseph.SwissEph;

/**
 * A fixed set of charts across eras and latitudes, and what this build answers for them (J15).
 *
 * <p><b>What the row asked for, and what this is honestly able to be.</b> The master list wanted
 * "a systematic regression corpus of known charts with expected positions across eras and
 * latitudes". {@code calibration-corpus.tsv} was never that - it is a corpus of charts used to
 * calibrate prominence weighting, with no positions in it at all.
 *
 * <p><b>The expected positions here are this build's own, and that is stated rather than hidden.</b>
 * There is no independent authority on this machine to check them against: the Swiss Ephemeris is
 * the authority, and comparing it to itself proves nothing about accuracy. So the file is a
 * <i>drift</i> corpus - it answers "has anything changed since it was taken", which is the question
 * a regression actually asks - and {@code EphemerisCorpusCheck} carries the other half: invariants
 * that are true of the sky rather than of this build, and which a wrong ephemeris would break.
 * Read the two together; neither alone is what the row wanted.
 *
 * <p><b>The source column is the point of the file as much as the longitudes.</b> Each row records
 * whether the answer came from the ephemeris files, from the built-in approximation, or not at all.
 * A body that quietly starts falling back - which is what {@code semo_18.se1}'s absence did to the
 * North Node for the whole life of this project - changes that column without moving the longitude
 * enough for anybody to notice.
 *
 * <p><b>It cannot be regenerated by accident.</b> {@code main} refuses without an explicit
 * acknowledgement argument, for {@code GenerateExtraBodies}' reason: a corpus of expectations that
 * any run can rewrite is not a corpus of expectations. Regenerating turns a red check green by
 * definition, so it must be a thing somebody chose to do.
 */
public final class EphemerisCorpus {

    private EphemerisCorpus() { }

    /** Where the corpus lives, beside VERSION and known-red.txt rather than in the data folder. */
    public static final String FILE = "ephemeris-corpus.tsv";

    /** What {@code main} must be given before it will overwrite the file. */
    public static final String ACKNOWLEDGE = "--overwrite-the-expectations";

    /** How far a recomputed longitude may move before it counts as drift, in degrees. */
    public static final double TOLERANCE = 1e-6;

    /**
     * The instants. Chosen for the boundaries rather than for their charts.
     *
     * <b>Two of these are outside the files' reach on purpose.</b> 1500 is before
     * {@code sepl_18.se1} begins and 2450 is after it ends, so both rows record a fall back to the
     * approximation and the asteroids failing outright. That behaviour is as much a part of what
     * this build does as the positions are, and it is the part nobody would notice changing.
     */
    static final String[][] ERAS = {
        {"1500", "1500", "6", "1", "12.0"},
        {"1800", "1800", "1", "1", "0.0"},
        {"1850", "1850", "3", "21", "6.0"},
        {"1900", "1900", "12", "25", "18.0"},
        {"1950", "1950", "7", "4", "9.5"},
        {"1975", "1975", "7", "4", "4.25"},
        {"2000", "2000", "1", "1", "12.0"},
        {"2026", "2026", "9", "28", "0.0"},
        {"2100", "2100", "2", "28", "23.9833"},
        {"2200", "2200", "11", "11", "11.1833"},
        {"2399", "2399", "12", "31", "12.0"},
        {"2450", "2450", "1", "1", "12.0"},
    };

    /**
     * The places. Latitude is what the angles depend on; the bodies do not depend on it at all,
     * which is itself an invariant the check asserts.
     *
     * <b>Two of them are above and below the polar circles</b>, where Placidus has no answer and
     * the app substitutes Porphyry. A corpus "across latitudes" that stopped at the temperate zone
     * would miss the one latitude band where the house code does something different.
     */
    static final String[][] PLACES = {
        {"greenwich", "51.4779", "-0.0015"},
        {"sydney", "-33.8688", "151.2093"},
        {"equator", "0.0", "-78.5"},
        {"longyearbyen", "78.2232", "15.6267"},
        {"ushuaia", "-54.8019", "-68.3029"},
    };

    /** The house system every chart here is cast in. */
    static final char HOUSES = 'P';

    /** One measured value: which chart, which point, what it said and where it came from. */
    public static final class Row {
        public final String era;
        public final String place;
        public final String point;
        public final double lon;
        public final String source;

        Row(String era, String place, String point, double lon, String source) {
            this.era = era;
            this.place = place;
            this.point = point;
            this.lon = lon;
            this.source = source;
        }

        /** The key a stored row and a recomputed one are matched on. */
        public String key() {
            return era + "\t" + place + "\t" + point;
        }
    }

    /** The Julian day of an era, by its id. */
    public static double jdOf(String[] era) {
        return new SweDate(Integer.parseInt(era[1]), Integer.parseInt(era[2]),
            Integer.parseInt(era[3]), Double.parseDouble(era[4])).getJulDay();
    }

    /**
     * Every chart in the corpus, computed now.
     *
     * <b>One {@link SwissEph} for the whole walk</b>, as the app uses one - the library caches
     * per instance, and a fresh instance per chart would be measuring a colder machine than the
     * one the app runs on.
     */
    public static java.util.List<Row> measure() {
        java.util.List<Row> out = new java.util.ArrayList<>();
        SwissEph sw = new SwissEph(Ephemeris.PATH);
        for (String[] era : ERAS) {
            double jd = jdOf(era);
            for (String[] place : PLACES) {
                ChartFrame f = ChartFrame.compute(sw, jd, Double.parseDouble(place[1]),
                    Double.parseDouble(place[2]), HOUSES, false, 0.0);
                for (int i = 0; i < Bodies.count(); i++) {
                    ChartFrame.Body b = f.bodies[i];
                    String name = Bodies.at(i).name;
                    if (b == null || !b.ok) {
                        out.add(new Row(era[0], place[0], name, Double.NaN, "none"));
                    } else {
                        // A registry point that is computed from the chart rather than looked
                        // up - a lot, the south node, an angle - never went near the ephemeris,
                        // so giving it an ephemeris source word would be inventing one.
                        out.add(new Row(era[0], place[0], name, b.lon,
                            Bodies.at(i).source == Bodies.Source.EPHEMERIS ? sourceOf(b)
                                : "derived"));
                    }
                }
                // The angles, which are the only thing in a chart that depends on the place.
                //
                // <b>Prefixed, because the registry has points of these names too.</b> Written
                // as plain "Ascendant" and "Vertex" they collided with the registry's own rows
                // - 120 of 2,400 - and a map keyed on the point silently kept one of each pair,
                // so the corpus was 5% smaller than the walk that made it and the check reported
                // drift on its own first run. The house call's answer and the registry's answer
                // for the same angle are two measurements, and they are recorded as two.
                out.add(new Row(era[0], place[0], "houses:Ascendant", f.asc, "houses"));
                out.add(new Row(era[0], place[0], "houses:Midheaven", f.mc, "houses"));
                out.add(new Row(era[0], place[0], "houses:ARMC", f.armc, "houses"));
                out.add(new Row(era[0], place[0], "houses:Vertex", f.vertex, "houses"));
            }
        }
        return out;
    }

    /**
     * Where a body's answer came from, as one word.
     *
     * <b>Read off the return code, which is not the same as proof the file was read.</b> Measured
     * 28 Sep with the Moon's file missing, the Moon still reports SWIEPH. So this column says what
     * the library claims, and a change in it is still worth catching - it is the only signal there
     * is, not a guarantee.
     */
    static String sourceOf(ChartFrame.Body b) {
        int rc = b.returnCode;
        if (rc < 0) {
            return "error";
        }
        if ((rc & de.thmac.swisseph.SweConst.SEFLG_JPLEPH) != 0) {
            return "jpl";
        }
        if ((rc & de.thmac.swisseph.SweConst.SEFLG_SWIEPH) != 0) {
            return "files";
        }
        if ((rc & de.thmac.swisseph.SweConst.SEFLG_MOSEPH) != 0) {
            return "approximation";
        }
        // Zero: this body was never asked of the ephemeris at all. Everything computed rather
        // than looked up is labelled "derived" before it reaches here, so a row saying this is
        // a point that should have been asked for and was not - worth a word of its own.
        return "unasked";
    }

    // ------------------------------------------------------------------ the file

    /** The stored corpus, by {@link Row#key}, or an empty map when there is no file. */
    public static java.util.Map<String, Row> read(java.io.File file) throws java.io.IOException {
        java.util.Map<String, Row> out = new java.util.LinkedHashMap<>();
        if (!file.isFile()) {
            return out;
        }
        for (String line : new String(java.nio.file.Files.readAllBytes(file.toPath()),
                java.nio.charset.StandardCharsets.UTF_8).split("\r?\n")) {
            if (line.startsWith("#") || line.trim().isEmpty() || line.startsWith("era\t")) {
                continue;
            }
            String[] bits = line.split("\t");
            if (bits.length < 5) {
                continue;
            }
            // <b>A row that will not parse becomes a row saying so, rather than an exception.</b>
            // Mutating one longitude to something unreadable took the check's first part out with
            // a NumberFormatException, and a part that crashes reports no failures at all - the
            // failure mode four suites in this project have already had. Now it fails by name.
            Row r;
            try {
                r = new Row(bits[0], bits[1], bits[2],
                    "nan".equalsIgnoreCase(bits[3]) ? Double.NaN : Double.parseDouble(bits[3]),
                    bits[4]);
            } catch (NumberFormatException bad) {
                r = new Row(bits[0], bits[1], bits[2], Double.NaN, "malformed");
            }
            out.put(r.key(), r);
        }
        return out;
    }

    /** The file's text, header and all, so the writer and the check agree on the format. */
    static String compose(java.util.List<Row> rows) {
        StringBuilder sb = new StringBuilder();
        sb.append("# Ourania ephemeris corpus (J15) - GENERATED, and generated deliberately.\n");
        sb.append("#\n");
        sb.append("# WHAT THIS IS: the positions this build answers for a fixed set of charts,\n");
        sb.append("# so that a change to the ephemeris path shows up as a diff instead of as a\n");
        sb.append("# chart that is quietly a little different. ").append(ERAS.length)
            .append(" instants from 1500 to 2450 x ")
            .append(PLACES.length).append(" places from the equator to 78N.\n");
        sb.append("#\n");
        sb.append("# WHAT THIS IS NOT: an accuracy corpus. These numbers came from this build;\n");
        sb.append("# checking them against it proves only that nothing has moved. The assertions\n");
        sb.append("# that test whether the sky is RIGHT are in EphemerisCorpusCheck, and they are\n");
        sb.append("# invariants - the tropical year, the synodic month, the sidereal periods -\n");
        sb.append("# which are true of the sky rather than of this program.\n");
        sb.append("#\n");
        sb.append("# THE SOURCE COLUMN MATTERS AS MUCH AS THE LONGITUDE. 'files' is the Swiss\n");
        sb.append("# Ephemeris data; 'approximation' is the built-in Moshier fall back, which is\n");
        sb.append("# close enough that nobody notices it happening; 'error' is a point the chart\n");
        sb.append("# does not get at all. A row moving from files to approximation is the defect\n");
        sb.append("# this file exists to catch.\n");
        sb.append("# A derived point - an angle, a lot, the south node - is labelled\n");
        sb.append("# 'derived', because no ephemeris call answers it; 'houses' is the four\n");
        sb.append("# angles the house call returns.\n");
        sb.append("#\n");
        sb.append("# Regenerate with:\n");
        sb.append("#   java -cp \"src\\main\\java;lib\\*\" ")
            .append(EphemerisCorpus.class.getName()).append(' ').append(ACKNOWLEDGE).append('\n');
        sb.append("# Houses: ").append(HOUSES)
            .append(".  Zodiac: tropical.  Settings: a fresh install's defaults.\n");
        sb.append("era\tplace\tpoint\tlongitude\tsource\n");
        for (Row r : rows) {
            sb.append(r.era).append('\t').append(r.place).append('\t').append(r.point)
                .append('\t')
                .append(Double.isNaN(r.lon) ? "nan" : String.format("%.9f", r.lon))
                .append('\t').append(r.source).append('\n');
        }
        return sb.toString();
    }

    /**
     * Rewrites the corpus, and refuses to unless it was asked to by name.
     *
     * <b>J10's rule, applied to expectations rather than to prose.</b> A generator that any run
     * can trip turns every drift into a green check, which is worse than having no corpus: it
     * looks like the question was asked.
     */
    public static void main(String[] args) throws Exception {
        boolean acknowledged = false;
        for (String a : args) {
            acknowledged |= ACKNOWLEDGE.equals(a);
        }
        if (!acknowledged) {
            System.out.println("This rewrites the expected positions in " + FILE + ".");
            System.out.println("Every drift EphemerisCorpusCheck would have reported becomes");
            System.out.println("correct by definition the moment it runs. If that is what you");
            System.out.println("want, say so:");
            System.out.println();
            System.out.println("  java -cp \"src\\main\\java;lib\\*\" "
                + EphemerisCorpus.class.getName() + " " + ACKNOWLEDGE);
            System.exit(1);
            return;
        }
        // <b>A fresh install's settings, or the corpus is a record of one reader's
        // preferences.</b> Generated once without this, the file disagreed with the check on 120
        // longitudes and 1,125 source words - because the node variant and the enabled body set
        // are settings, so the generator measured David's chart selection and the suite measured
        // the defaults. This is J14's rule, and the corpus needed it for the same reason the
        // suites did: a file that changes with a preference cannot say whether the code changed.
        com.zodiacomputing.ourania.gui.Settings.useScratchFile();
        java.util.List<Row> rows = measure();
        java.io.File file = new java.io.File(FILE);
        java.nio.file.Files.write(file.toPath(),
            compose(rows).getBytes(java.nio.charset.StandardCharsets.UTF_8));
        System.out.println("Wrote " + rows.size() + " rows to " + file.getAbsolutePath());
    }
}
