package com.zodiacomputing.ourania.gui;

import java.util.HashMap;
import java.util.Map;

public class InterpretationData {
    public static final Map<String, String> DATA = new HashMap<>();
    
    static {
        DATA.put("DynAscText", "\"The speed of the ascendant is, by nature, not valuable in terme of astrology because of the very shot period but it was %1$s/day.r\n As the ascendant represents the intersection between the horizon and the path of the sun (or solar ecliptic), the ecliptic latitude is always zero but the longitude was %2$s. With that longitude, rising sign is into %3$s sign.\"");
        DATA.put("DynJupiText", "\"At this date, the solar system biggest planet apparent speed was %1$s/day. r\n The latitude is %2$s and the longitude is %3$s. With that longitude, Jupiter is into %4$s sign and placidus house %5$s.\"");
        DATA.put("DynMarsText", "\"Mars is going around the sun in 687 days. As mars is the first planet which is located after the earth, that means mars (and all the following planets) could have a retrograde motion (negative speed). At this date, the apparent speed was %1$s/day.r\n The latitude is %2$s and the longitude is %3$s. With that longitude, the red planet is into %4$s sign and placidus house %5$s.\"");
        DATA.put("DynMcText", "\"he speed of the Midheaven is , by nature, not valuable in terme of astrology because of the very shot period but it was %1$s/day.r\n Since the Midheaven represents the crossing of the meridian and the solar ecliptic (or Earth orbit), the ecliptic latitude is always zero but the longitude was %2$s. With that longitude, Midheaven is into %3$s sign.\"");
        DATA.put("DynMercText", "\"Mercury is going around the sun in 88 days, but the speed is not constant. at this date, the apparent speed was %1$s/day.r\n Mercury orbit has 9° obliquity compared to the ecliptic so the latitude have some variations, so the latitude is %2$s. The longitude value, %3$s, is not far from the Sun one because of their proximity (%4$s difference). With that longitude, Mercury is into %5$s sign and placidus house %6$s.\"");
        DATA.put("DynMoonText", "\"The above picture represent the moon like it was enlightened on the %1$s.r\n As the moon is going around earth in about 27 days, 7 hours and 43 minutes, it's apparent speed is quite constant and equal to %2$s/day.r\n As The Moon orbit is almost aligned to the Solar system ecliptic (or earth orbit), the moon ecliptic latitude is quite low at %3$s and the ecliptic longitude is %4$s. With that longitude, the Moon is into %5$s sign and placidus house %6$s.\"");
        DATA.put("DynNeptText", "\"The Neptun apparent speed was %1$s/day.r\n The latitude is %2$s and the longitude is %3$s. With that longitude, Neptun is into %4$s sign and placidus house %5$s.\"");
        DATA.put("DynPlutText", "\"The lastest planet of the solar system need 248 years to go around the sun. So the pluto apparent speed was %1$s/day.r\n The latitude is %2$s and the longitude is %3$s. With that longitude, Pluto is into %4$s sign and placidus house %5$s.\"");
        DATA.put("DynSatuText", "\"The apparent speed of the ringed planet was %1$s/day.r\n The latitude is %2$s and the longitude is %3$s. With that longitude, Saturn is into %4$s sign and placidus house %5$s.\"");
        DATA.put("DynSunText", "\"The earth is going around the sun in 365,25 days, so the sun's apparent speed is constant and equal to %1$s/day.r\n As the sun is the center of the solar system ecliptic, the sun ecliptic latitude is always null. the sun ecliptic longitude is %2$s. With that longitude, the Sun is into %3$s sign and placidus house %4$s.\"");
        DATA.put("DynUranText", "\"At this date, the uranus apparent speed was %1$s/day.r\n The latitude is %2$s and the longitude is %3$s. With that longitude, Uranus is into %4$s sign and placidus house %5$s.\"");
        DATA.put("DynVenuText", "\"Venus is going around the sun in 224 days so we consider this planet to be fast because it is inferior to 1 year. At this date, the apparent speed was %1$s/day.r\n The latitude is %2$s and the longitude is %3$s. With that longitude, Venus is into %4$s sign and placidus house %5$s.\"");
        DATA.put("StaAscText", "The Ascendant is the easternmost point of the horizon where the sun rises. Similarly, it represent the person in the manner it has to present to the world: how it looks at first, and how it behaves in society.");
        DATA.put("StaCereText", "Ceres was the first to be discovered in the asteroid belt. It has since been reclassified as a dwarf planet, which would make Ceres at least as important as Pluto in the astrological chart since they are both dwarf planets. Ceres was the sister of Zeus (Jupiter). She is the quintessential Earth Mother, and rules over food, cooking and nutrition. Wherever she appears in your chart, she shows how best you feel nurtured. This is also the area where you can easily provide love and comfort. Your Ceres Sign influences mothering, hard work, parenting, and gardening as well. It will show how well we go with the flow… the universal one, that is. This is the unification of both giving and receiving through ourselves as an exchange of energy. Ceres is associated with fertility, the uterus and stomach. On her negative side, she influences grief, work problems, eating disorders, custody issues and kidnapping. She may influence low self esteem, fear of abundance, feelings of abandonment or unworthiness, over-attachment, possessiveness, parent-child complexes and barrenness.");
        DATA.put("StaChirText", "Chiron is located between Saturn and Uranus and is considered a centaur asteroid. In reality it is a comet nucleus. It was discovered in 1977. Also known as the Planet of Healing, Chiron deals with all aspects of health and disease and how they affect our spiritual path. Chiron was wounded himself, and despite his great skills, he never healed. He symbolizes everyone who finds their strength through their suffering. Everyone gets wounded in some manner. Whatever our wounds are, Chiron influences us to overcome our condition and go on. Like Chiron, we may find that in healing others we gain some insight and salvation even though we are unable to fully heal ourselves. Chiron has an unusual orbit, rather like Pluto. Many astrologers think of Chiron as a mediator between Uranus and Saturn. Chiron gives wisdom and patience as well as mastery over the darkness of our souls. Our wounds are gifts when looked at from a different angle. They give us character, lessons in life and perseverance. Chiron teaches us these things whether we are ready to learn them or not.");
        DATA.put("StaJunoText", "\"Juno was the third asteroid to be discovered. Juno is the wife of Jupiter. She has some similarities to Venus, but while Venus sparks that initial attraction, Juno makes the commitment. She sings of soul mates. As she moves through the sky, the face of relationships change, but she still stands for commitment of one kind or another. Where you find Juno in your chart is where you may meet someone that you will remain with for a long relationship. She covers marriage, fashion and beauty. She is the patron of relationships and true love. Diplomacy is part of her sphere. She has influence with the weather, flowers, fairness and female genitalia. She also dealt with many of Jupiter's infidelities, and thus has influence over the negative issues of spouse abuse, powerlessness, women's rights (both positive and negative), rage, inferiority complexes and unfairness. She may also affect issues of denial, betrayal, inequality and of course bitterness.\"");
        DATA.put("StaJupiText", "Jupiter, king of the gods, is the manager of Olympus and he who decides disputes between the gods. However, it is the first to violate its principles, which multiplies the inveterate seducer infidelities (which are followed by birth), even abuse their power. It is therefore only pass on his principles and enforced by the greatest number. It has a function and expansive vision.");
        DATA.put("StaMarsText", "Mars, the warrior god, is the heart of the action its purest form: Desire, libido man driving fetching means to an end. That this is the result of passion for Venus, his obedience to solar or relationship to other planets, Mars embodies a motor function for the person.");
        DATA.put("StaMcText", "The Midheaven is the highest point of the sky chart, symbolically what the person sucks the most, what makes it evolves. These valor represent the Midheaven are the ploughshare that traces the vocation of the person on earth. He speaks so well of the quarry.");
        DATA.put("StaMercText", "The god Mercury brings and translated the message from the gods to men. It is the intermediary between the first desire and final thought. Similarly, humans distinguish the I who wants against the Ithat thinks, he becomes aware of himself and able to speak. In this sense, Mercury is an expressive function.");
        DATA.put("StaMoonText", "The Moon allows animals (and the First Men as well) to see and live in fear of the night. Strongly tinged with unconscious, the Moon governs self-preservation, deep emotional reactions. These are highlighted by the sun, so the astrologer use to analyse jointly these two planets.");
        DATA.put("StaNeptText", "Neptune is the god of the seas. These are crossed by currents, unpredictable, opaque, incomprehensible. We only see the surface, through which it is believed guess the bottom, so that only Neptune knows. Neptune symbolizes both the Veil (or impressions), and when they pierce the surface, they are fertile, inspiration.");
        DATA.put("StaPalaText", "\"Pallas Athena was the second asteroid discovered. Named after Jupiter's daughter, Pallas Athena is intelligent and cerebral. She is the weaver of patterns, linking ideas together. She is strategic command in both the warrior and the peaceful general. Cities are her domain. She has an interconnection with Libra because of her focus on ideas. Like Libra, she can see both sides. She is not blind justice… she is only just. She is creative and artistic. She is a survivor. She expects everyone to claim their personal power. Where her influence falls is where you will find talents in the following areas. Jupiter's daughter carries influence over many things, such as the immune system, the arts, the father/daughter relationship, intuition, justice, wisdom, defense, horses and the kidneys. With her spotlight on daddy's little girl, Pallas Athena will help determine how you interpret your relationship with your father, and in turn how you treat all males in general. On her negative side, Pallas Athena touches on conflict, legal battles, injustice and illnesses due to a weakened immune system.\"");
        DATA.put("StaPlutText", "Pluto is the god of death, keeper of the underworld. He alone decides that a soul can be reincarnated or not. It is therefore the principal transformation of the person, purified in the underworld of the psyche. He can talk about the experiences the most intense and deeper than a person can live.");
        DATA.put("StaSatuText", "Ambitious, Saturn would rule over the gods in place of his brother, Titan. He then acceded to his request, provided that kills his offspring with his own hands. Saturn accepted this constraint, but failed to kill Zeus and his brothers who dethroned. Still, by this extreme behavior, it symbolizes the function responsible restrictrice.");
        DATA.put("StaSunText", "The sun helps plants grow, animals to see, eat, in short, life on earth. It symbolizes the vital need of the individual organism, the light coloring his life to its full development to the heavens.The consciousness of the Sun opposes the instinctiveness of the moon and are complementary in astrological interpretation.");
        DATA.put("StaUranText", "Uranus, the god of heaven, is the father of Venus and the ancestor of all the gods of Olympus. If Venus symbolizes love the individual, Uranus is the universal love of humanity in general. This is the ultimate source of progress, which is in the dispassionate abstractions, concepts of its mission. It represents the ideal in its construction.");
        DATA.put("StaVenuText", "\"Mythology relates that Uranus, the sky god, was emasculated, and its progenitors bodies dumped in the Netptun's ocean. Venus was born of the meeting of sky and sea abstract emotional. Its shell, it landed on earth and deal only with the environment the only emotions that she understands and nurtures: the passions. Venus takes on an emotional function.\"");
        DATA.put("StaVestText", "Vesta is the second largest asteroid in our solar system and the fourth to be discovered. Vesta is a sister of Jupiter, the virgin goddess. Vesta is the keeper of the hearth. She is focus and dedication. She is mental clarity and self-respect. Vesta brings out your purest potential and Essence into being. Vesta is organized and perfect. She has a talent for breaking things down into its components. She rules the metabolism and the upper intestine. She carries influence over locks and keys, sisters, security, investments, insurance, and inheritance. She is the epitome of the home and family, ritual, chastity and sexuality, and devotion. Her negative aspects include insecurity, lack of focus, promiscuity, segregation, secret societies and family troubles. There may be a fear of sex or intimacy, as well as an invalidation of self. Denial can be a big aspect when she is negative.");
        DATA.put("Stat_short_title", "Statistics");
        DATA.put("status_bar_notification_info_overflow", "999+");
    }
}
